// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/shaken1/ProjetoCompilador/token"
)

const (
	NoState    = -1
	NumStates  = 94
	NumSymbols = 102
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '-'
1: '+'
2: '*'
3: '/'
4: '%'
5: '='
6: '>'
7: '<'
8: '>'
9: '='
10: '<'
11: '='
12: '<'
13: '>'
14: ':'
15: '='
16: ','
17: ';'
18: '('
19: ')'
20: '{'
21: '}'
22: ','
23: 'E'
24: 'E'
25: '''
26: '\'
27: 'n'
28: '\'
29: 't'
30: ' '
31: '''
32: 'i'
33: 'f'
34: 'e'
35: 'l'
36: 's'
37: 'e'
38: 'w'
39: 'h'
40: 'i'
41: 'l'
42: 'e'
43: 'r'
44: 'e'
45: 't'
46: 'u'
47: 'r'
48: 'n'
49: 'f'
50: 'l'
51: 'o'
52: 'a'
53: 't'
54: 'c'
55: 'h'
56: 'a'
57: 'r'
58: 'v'
59: 'o'
60: 'i'
61: 'd'
62: 'p'
63: 'r'
64: 'n'
65: 't'
66: 'i'
67: 'n'
68: 't'
69: 'p'
70: 'r'
71: 'o'
72: 'c'
73: 'v'
74: 'a'
75: 'r'
76: 'o'
77: 'r'
78: 'a'
79: 'n'
80: 'd'
81: 'n'
82: 'o'
83: 't'
84: '_'
85: ','
86: '\t'
87: '\n'
88: '\r'
89: ' '
90: '*'
91: '*'
92: '\n'
93: '>'
94: '>'
95: '*'
96: '<'
97: '<'
98: '0'-'9'
99: 'A'-'Z'
100: 'a'-'z'
101: .
*/
